name: Beautiful Jekyll CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - uses: actions/checkout@v2
#      - name: Build the site in the jekyll/builder container
#        run: |
#          export JEKYLL_VERSION=3.8
#          docker run \
#          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#          -e PAGES_REPO_NWO=${{ github.repository }} \
#          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
              ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build
